### ISSUE TITLE
Unhandled exception

### ISSUE THREAD

**Issue by ShadowsTear** [SightstoneOfficial/LegendaryClient#202]
Pastebin link to log:
http://pastebin.com/ECsxPKtZ

**Comment by eddy5641** [comment]
News for OCE

**Comment by Dispersia** [comment]
might be the same thing that I fixed for LAN. Shadows are you compiling it yourself or using a release build? If so need to wait till the next actual release build. Sorry about that

**Comment by ShadowsTear** [comment]
using a release build :s

**Comment by Dispersia** [comment]
replace your executable with https://www.mediafire.com/?unmy31vg6q4ux1c (in the client folder) and tell me if this still occurs (rename to remove the 2 if needed, mediafire I think changed the naming, sorry!)

**Comment by ShadowsTear** [comment]
Still happens, with a different error though,
http://pastebin.com/np3S3vAr

**Comment by Dispersia** [comment]
Located the problem. Out of nowhere apparently for OCE they finally started using BroadcastMessage, which I never finished because they haven't used it for a very long time for any other server. I'll get it fixed when I'm done fixing this other thing. Again, thanks for the reports

**Comment by Dispersia** [comment]
Ya sorry this is taking a bit, I messed a few other things up and trying to get them fixed before I just push an update (since if no one can use it kinda ruins the purpose of fixing anything at all :P, sorry)

**Comment by ShadowsTear** [comment]
As a note, this also happens with PBE.

http://pastebin.com/LcBWa51T
