### ISSUE TITLE
Insta-crash when joining champ select

### ISSUE THREAD

**Issue by niktamerfdp** [SightstoneOfficial/LegendaryClient#384]
(28/06/2015 04:36) [LOG]: LegendaryClient Started Up Successfully
(28/06/2015 04:36) [LOG]: Switching to the page: LegendaryClient.Windows.PatcherPage
(28/06/2015 04:36) [EXCEPTION]: A first chance exception was thrown
(28/06/2015 04:36) [EXCEPTION]: Impossible de charger le fichier ou l'assembly 'mscorlib.XmlSerializers, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089' ou une de ses dépendances. Le fichier spécifié est introuvable.
(28/06/2015 04:36) [EXCEPTION]:    à System.Reflection.RuntimeAssembly._nLoad(AssemblyName fileName, String codeBase, Evidence assemblySecurity, RuntimeAssembly locationHint, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)
   à System.Reflection.RuntimeAssembly.nLoad(AssemblyName fileName, String codeBase, Evidence assemblySecurity, RuntimeAssembly locationHint, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)
(28/06/2015 04:36) [LOG]: Checking Plugin dependencies...
(28/06/2015 04:36) [LOG]: Plugin dependencies are installed
(28/06/2015 04:36) [LOG]: Newest DataDragon Version: 5.12.1
(28/06/2015 04:36) [LOG]: Current DataDragon Version: 5.12.1
(28/06/2015 04:36) [LOG]: DDragon Version (LOL Version) = 5.12.1
(28/06/2015 04:36) [LOG]: Newest Air Assets Version: 0.0.1.149
(28/06/2015 04:36) [LOG]: Current Air Assets Version: 0.0.1.149
(28/06/2015 04:36) [LOG]: Checking Theme...
(28/06/2015 04:36) [LOG]: Trying to detect League of Legends GameClient
(28/06/2015 04:36) [LOG]: League of Legends is located at: J:\Riotarded Games\
(28/06/2015 04:36) [LOG]: Latest League of Legends GameClient: 0.0.1.94
(28/06/2015 04:36) [LOG]: Checking if League of Legends is Up-To-Date
(28/06/2015 04:36) [LOG]: League of Legends is Up-To-Date
(28/06/2015 04:36) [LOG]: LegendaryClient Has Finished Patching
(28/06/2015 04:36) [LOG]: Switching to the page: LegendaryClient.Windows.LoginPage
(28/06/2015 04:36) [LOG]: rate+|+110
(28/06/2015 04:36) [LOG]: token+|+-tJgGJdjU9i1OCr+cxgxusSZVijQg+5DnSCsnAOsgH9MQ1vBBwhenex9ny95MQl0BSVvTWFUW0cspfUujZxoVHsFalaPry1n
(28/06/2015 04:36) [LOG]: reason+|+login_rate
(28/06/2015 04:36) [LOG]: status+|+LOGIN
(28/06/2015 04:36) [LOG]: delay+|+5000
(28/06/2015 04:36) [LOG]: inGameCredentials+|+{
  "inGame": false,
  "summonerId": null,
  "serverIp": null,
  "serverPort": null,
  "encryptionKey": null,
  "handshakeToken": null
}
(28/06/2015 04:36) [LOG]: user+|+NOPENOPENOPENOPENOPE{
}
(28/06/2015 04:36) [LOG]: Connected to EUW and logged in as Dirty Weaboo
(28/06/2015 04:36) [LOG]: Switching to the page: LegendaryClient.Windows.MainPage
(28/06/2015 04:37) [EXCEPTION]: A first chance exception was thrown
(28/06/2015 04:37) [EXCEPTION]: L'identité de l'application n'est pas définie.
(28/06/2015 04:37) [EXCEPTION]:    à System.Deployment.Application.ApplicationDeployment.get_CurrentDeployment()
(28/06/2015 04:37) [EXCEPTION]: A first chance exception was thrown
(28/06/2015 04:37) [EXCEPTION]: Le serveur distant a retourné une erreur : (404) Introuvable.
(28/06/2015 04:37) [EXCEPTION]:    à System.Net.HttpWebRequest.GetResponse()
(28/06/2015 04:37) [EXCEPTION]: A first chance exception was thrown
(28/06/2015 04:37) [EXCEPTION]: Le serveur distant a retourné une erreur : (404) Introuvable.
(28/06/2015 04:37) [EXCEPTION]:    à System.Net.WebClient.DownloadDataInternal(Uri address, WebRequest& request)
(28/06/2015 04:37) [LOG]: http://matchhistory.na.leagueoflegends.com/en/#match-details/EUW1/-2147483648/222364984?tab=overview
(28/06/2015 04:37) [LOG]: Switching to the page: LegendaryClient.Windows.PlayPage
(28/06/2015 04:37) [LOG]: Switching to the page: LegendaryClient.Windows.CreateCustomGamePage
(28/06/2015 04:37) [LOG]: Message received! The type is: LegendaryClient.Logic.Riot.Platform.LobbyStatus
(28/06/2015 04:37) [LOG]: Switching to the page: LegendaryClient.Windows.CustomGameLobbyPage
(28/06/2015 04:37) [EXCEPTION]: A first chance exception was thrown
(28/06/2015 04:37) [EXCEPTION]: La valeur était trop grande ou trop petite pour un Int32.
(28/06/2015 04:37) [EXCEPTION]:    à System.Convert.ToInt32(Double value)
(28/06/2015 04:37) [EXCEPTION]: A first chance exception was thrown
(28/06/2015 04:37) [EXCEPTION]: La valeur était trop grande ou trop petite pour un Int32.
(28/06/2015 04:37) [EXCEPTION]:    à System.Convert.ToInt32(Double value)
   à LegendaryClient.Windows.CustomGameLobbyPage.<>c__DisplayClass4.<<Lobby_OnMessageReceived>b__2>d__7.MoveNext()
--- Fin de la trace de la pile à partir de l'emplacement précédent au niveau duquel l'exception a été levée ---
   à System.Runtime.CompilerServices.AsyncMethodBuilderCore.<ThrowAsync>b__4(Object state)
(28/06/2015 04:37) [UNHANDLEDEXCEPTION]: An unhandled exception was thrown
(28/06/2015 04:37) [UNHANDLEDEXCEPTION]: La valeur était trop grande ou trop petite pour un Int32.
(28/06/2015 04:37) [UNHANDLEDEXCEPTION]:    à System.Convert.ToInt32(Double value)
   à LegendaryClient.Windows.CustomGameLobbyPage.<>c__DisplayClass4.<<Lobby_OnMessageReceived>b__2>d__7.MoveNext()
--- Fin de la trace de la pile à partir de l'emplacement précédent au niveau duquel l'exception a été levée ---
   à System.Runtime.CompilerServices.AsyncMethodBuilderCore.<ThrowAsync>b__4(Object state)
   à System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   à MS.Internal.Threading.ExceptionFilterHelper.TryCatchWhen(Object source, Delegate method, Object args, Int32 numArgs, Delegate catchHandler)
   à System.Windows.Threading.DispatcherOperation.InvokeImpl()
   à System.Windows.Threading.DispatcherOperation.InvokeInSecurityContext(Object state)
   à System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   à System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   à System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   à System.Windows.Threading.DispatcherOperation.Invoke()
   à System.Windows.Threading.Dispatcher.ProcessQueue()
   à System.Windows.Threading.Dispatcher.WndProcHook(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   à MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   à MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   à System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   à MS.Internal.Threading.ExceptionFilterHelper.TryCatchWhen(Object source, Delegate method, Object args, Int32 numArgs, Delegate catchHandler)
   à System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
   à MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
   à MS.Win32.UnsafeNativeMethods.DispatchMessage(MSG& msg)
   à System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)
   à System.Windows.Threading.Dispatcher.PushFrame(DispatcherFrame frame)
   à System.Windows.Threading.Dispatcher.Run()
   à System.Windows.Application.RunDispatcher(Object ignore)
   à System.Windows.Application.RunInternal(Window window)
   à System.Windows.Application.Run(Window window)
   à LegendaryClient.App.Main()

(it's french)

http://i.imgur.com/IMW9VGE.jpg
http://i.imgur.com/eNm1hyh.png

I didn't try in PvP queue, it was only bot and custom (I assume it always crash).
(my first time reporting a bug, excuse me if it ain't... good)

**Comment by secretdataz** [comment]
Is this on EUW?

**Comment by niktamerfdp** [comment]
Yes, this is on EUW.

**Comment by secretdataz** [comment]
Alright, I'm creating an account and stuff.

**Comment by secretdataz** [comment]
Seems like number of games on EUW is larger than max value of a 32 bit integer.

**Comment by niktamerfdp** [comment]
Ow, ok. Is it fixable?

**Comment by secretdataz** [comment]
Should be an easy one. Currently testing the fix.

**Comment by niktamerfdp** [comment]
Okay, that was fast ^^ Thanks

**Comment by secretdataz** [comment]
Ah, I have a problem. I need a working account. My new account doesn't work for me on LC and I don't want to download EUW client. Could you help me? :3

**Comment by mlpEpilepsy** [comment]
Okay, wait a minute

**Comment by niktamerfdp** [comment]
How may I help you?

**Comment by secretdataz** [comment]
Email me an account with any random summoner name.

**Comment by niktamerfdp** [comment]
Sent

**Comment by secretdataz** [comment]
Please create my summoner name for me >.<

**Comment by niktamerfdp** [comment]
I already did ^^

edit: screencap http://i.imgur.com/wLtGIjg.png

**Comment by secretdataz** [comment]
The fix is just a type change (int32 to int64) and I'm tired with my hacky client. So, I've pushed the change (2 character change lol). Please test it yourself and tell me if it crashes on somewhere else.
And remember to use Debug profile when debugging with Visual Studio.

**Comment by niktamerfdp** [comment]
Okay, testing

**Comment by niktamerfdp** [comment]
By the way, I don't compile it myself and I only use the LegendaryClient updater. I just clicked "debug" when it crashed.

**Comment by secretdataz** [comment]
That's fine hehe. Please close the issue if it doesn't crash anymore.

**Comment by niktamerfdp** [comment]
Oh, I was downloading the .zip to compile it myself because I thought the updater didn't update yet. Well then, it still crashes.

But from what I see the change has been made to "CustomGameLobbyPage.xaml.cs"

I dunno if you exactly got the problem. It's basically that whenever I get onto the character screen select, it crashes. Bot game, pvp game, custom game, all of them. It doesn't seem custom game related, does it?

**Comment by secretdataz** [comment]
No. The problem seems to be specific on EUW.

**Comment by niktamerfdp** [comment]
Okay. Trying to compile it

**Comment by niktamerfdp** [comment]
Alright, works fine when I compiled it. However, the updater didn't catch the update. Oh and I also opened another bug (champion rotations ain't the right one).

Thanks for the reactivity

**Comment by voshond** [comment]
Right now The updater won't Update The Client right now, i think it only updates needed assets from server or the database we need. Ppl need to download from the latest build in appvoyer (that build passing icon there). I think this is planned in the future but I'm only an UI guy.
